/** WARNING: This file was auto-generated by svgr. Do not edit! */
;
import * as React from 'react';
import { forwardRef, type Ref, type SVGProps } from 'react';
const ArrowLeftIcon = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => {
  return <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" role="presentation" ref={ref} {...props}><path d="M10 5.75L3.75 12L10 18.25M4.5 12H20.25" stroke="currentcolor" strokeWidth={1.5} strokeLinecap="square" /></svg>;
});
export default ArrowLeftIcon;