/** WARNING: This file was auto-generated by svgr. Do not edit! */
;
import * as React from 'react';
import { forwardRef, type Ref, type SVGProps } from 'react';
const SettingsGear1Icon = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => {
  return <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" role="presentation" ref={ref} {...props}><path d="M12 2.75L20.25 7.49995V16.4999L12 21.2499L3.75 16.5002V7.49992L12 2.75Z" stroke="currentcolor" strokeWidth={1.5} strokeLinecap="square" /><path d="M15.25 12C15.25 13.7949 13.795 15.25 12 15.25C10.2051 15.25 8.75 13.7949 8.75 12C8.75 10.2051 10.2051 8.75 12 8.75C13.795 8.75 15.25 10.2051 15.25 12Z" stroke="currentcolor" strokeWidth={1.5} strokeLinecap="square" /></svg>;
});
export default SettingsGear1Icon;