# /// script
# requires-python = ">=3.12"
# dependencies = ["pyyaml>=6", "jsonschema>=4.20"]
# ///
"""Build the example catalog from the front matter in examples/*/README.md.

Writes the catalog section of README.md and registry.yaml, which the docs.x.ai
build reads. With --check, writes nothing and fails if either file is out of
date, if any front matter is invalid, or if a relative link in a markdown file
points at something that doesn't exist.

    uv run catalog/build.py           # regenerate README.md and registry.yaml
    uv run catalog/build.py --check   # what CI and the pre-commit hook run
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote

import jsonschema
import yaml

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
README = ROOT / "README.md"
REGISTRY = ROOT / "registry.yaml"
SCHEMA = Path(__file__).resolve().parent / "schema.json"

CATALOG_START = "<!-- catalog:start -->"
CATALOG_END = "<!-- catalog:end -->"
TYPE_HEADINGS = {"recipe": "Recipes", "guide": "Guides", "app": "Apps"}
LEVELS = ["beginner", "intermediate", "advanced"]
LANGUAGE_NAMES = {"python": "Python", "typescript": "TypeScript", "swift": "Swift", "kotlin": "Kotlin"}
REGISTRY_HEADER = (
    "# Generated by catalog/build.py from the front matter in examples/*/README.md.\n"
    "# The docs.x.ai build reads this file, so don't edit it by hand.\n\n"
)

FRONT_MATTER = re.compile(r"---\n(.*?)\n---\n", re.DOTALL)
FENCED_CODE = re.compile(r"^(```|~~~).*?^\1", re.DOTALL | re.MULTILINE)
INLINE_CODE = re.compile(r"`[^`\n]*`")
LINK_TARGET = re.compile(r"\]\(\s*<?([^)\s>]+)>?(?:\s+\"[^\"]*\")?\s*\)|\bhref=\"([^\"]+)\"")


def read_front_matter(readme: Path) -> dict:
    match = FRONT_MATTER.match(readme.read_text(encoding="utf-8"))
    if not match:
        raise ValueError("must start with a front matter block between --- lines")
    meta = yaml.safe_load(match.group(1))
    if meta is None:
        meta = {}
    if not isinstance(meta, dict):
        raise ValueError("front matter must be a YAML mapping")
    if isinstance(meta.get("date"), dt.date):
        meta["date"] = meta["date"].isoformat()
    return meta


def load_examples() -> tuple[list[dict], list[str]]:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    validator = jsonschema.Draft202012Validator(schema, format_checker=jsonschema.FormatChecker())
    examples, errors = [], []

    for folder in sorted(p for p in EXAMPLES.iterdir() if p.is_dir()):
        readme = folder / "README.md"
        where = readme.relative_to(ROOT)
        if not readme.is_file():
            errors.append(f"{folder.relative_to(ROOT)}: every example folder needs a README.md with front matter")
            continue
        try:
            meta = read_front_matter(readme)
        except (ValueError, yaml.YAMLError) as exc:
            errors.append(f"{where}: {exc}")
            continue

        problems = [f"{where}: {error.message}" for error in validator.iter_errors(meta)]
        if not problems:
            code = {lang: meta.get("code", {}).get(lang, lang) for lang in meta["languages"]}
            for lang, rel in code.items():
                if not (folder / rel).is_dir():
                    problems.append(f"{where}: {lang} code folder '{rel}' doesn't exist")
            for key in ("notebook", "cover"):
                if key in meta and not (folder / meta[key]).is_file():
                    problems.append(f"{where}: {key} '{meta[key]}' doesn't exist")
            examples.append({**meta, "slug": folder.name, "code": code})
        errors += problems

    return examples, errors


def sort_key(example: dict) -> tuple[int, str]:
    return LEVELS.index(example["level"]), example["title"].lower()


def render_catalog(examples: list[dict]) -> str:
    lines = []
    for kind, heading in TYPE_HEADINGS.items():
        group = sorted((e for e in examples if e["type"] == kind), key=sort_key)
        if not group:
            continue
        lines += [f"### {heading}", "", "| Example | What you'll learn | Level | Code |", "| --- | --- | --- | --- |"]
        for example in group:
            base = f"examples/{example['slug']}"
            code = " · ".join(
                f"[{LANGUAGE_NAMES[lang]}]({base}/{'' if rel == '.' else rel.strip('/') + '/'})"
                for lang, rel in example["code"].items()
            )
            description = example["description"].replace("|", "\\|")
            lines.append(f"| [{example['title']}]({base}/) | {description} | {example['level'].capitalize()} | {code} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_readme(catalog: str) -> str:
    text = README.read_text(encoding="utf-8")
    if CATALOG_START not in text or CATALOG_END not in text:
        raise SystemExit(f"README.md needs {CATALOG_START} and {CATALOG_END} markers around the catalog")
    before, rest = text.split(CATALOG_START, 1)
    _, after = rest.split(CATALOG_END, 1)
    return f"{before}{CATALOG_START}\n{catalog}{CATALOG_END}{after}"


def render_registry(examples: list[dict]) -> str:
    entries = []
    for example in sorted((e for e in examples if not e.get("hide_from_docs")), key=sort_key):
        base = f"examples/{example['slug']}"
        entry = {"title": example["title"]}
        if "seo_title" in example:
            entry["seo_title"] = example["seo_title"]
        entry["path"] = f"{base}/{example.get('notebook', 'README.md')}"
        if "cover" in example:
            entry["image"] = f"{base}/{example['cover']}"
        if "icon" in example:
            entry["icon"] = example["icon"]
        entry["description"] = example["description"]
        entry["date"] = dt.date.fromisoformat(example["date"])
        entry["authors"] = example["authors"]
        entry["tags"] = example["capabilities"]
        entry["type"] = example["type"]
        entry["level"] = example["level"]
        entry["languages"] = example["languages"]
        entries.append(entry)
    return REGISTRY_HEADER + yaml.safe_dump(entries, sort_keys=False, allow_unicode=True, width=1000)


def markdown_files() -> list[Path]:
    listed = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "*.md"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout.split()
    return [ROOT / name for name in listed if (ROOT / name).is_file()]


def broken_links() -> list[str]:
    broken = []
    for path in markdown_files():
        text = INLINE_CODE.sub("", FENCED_CODE.sub("", path.read_text(encoding="utf-8")))
        for match in LINK_TARGET.finditer(text):
            target = match.group(1) or match.group(2)
            if re.match(r"^([a-z][a-z0-9+.-]*:|#|//)", target, re.IGNORECASE):
                continue
            relative = unquote(target.split("#", 1)[0].split("?", 1)[0])
            if not relative:
                continue
            resolved = ROOT / relative.lstrip("/") if relative.startswith("/") else path.parent / relative
            if not resolved.exists():
                broken.append(f"{path.relative_to(ROOT)}: {target}")
    return broken


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail instead of writing if anything is out of date")
    args = parser.parse_args()

    examples, errors = load_examples()
    if errors:
        print("Front matter problems:\n  " + "\n  ".join(errors), file=sys.stderr)
        return 1

    outputs = {README: render_readme(render_catalog(examples)), REGISTRY: render_registry(examples)}
    stale = [path for path, text in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != text]

    if not args.check:
        for path in stale:
            path.write_text(outputs[path], encoding="utf-8")
            print(f"Updated {path.relative_to(ROOT)}")

    problems = [f"{path.relative_to(ROOT)} is out of date. Run: uv run catalog/build.py" for path in stale if args.check]
    problems += [f"Broken link in {link}" for link in broken_links()]
    if problems:
        print("\n".join(problems), file=sys.stderr)
        return 1
    print(f"Catalog OK: {len(examples)} examples, all relative links resolve")
    return 0


if __name__ == "__main__":
    sys.exit(main())
